#cors:
#  originPatterns: http://localhost:3000,http://localhost:8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fake-shop-users?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    url: jdbc:postgresql://localhost:5432/fake-shop-users?useTimezone=true&serverTimezone=UTC
    user: root
    password: admin
  kafka:
    consumer:
      group-id: fake-shop-users
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092