version: '3'

services:

#  app:
#    depends_on:
#      - postgres
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: on-failure
#    ports:
#      - "8080:8080"

  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=fake-shop-users